language: node_js
node_js:
  - "4.4.5"
env:
  - NODE_ENV:test
after_success:
  - "npm install coveralls@2.11.4 && cat ./client/__coverage__/phantomjs/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
